### ISSUE TITLE
Rpi: Unable to view lib folder

### ISSUE THREAD

**Issue by Enforcer007** [monkey/monkey#190]
Though "./configure --enable-shared" script is run followed by "make", lib folder is not created.

**Comment by edsiper** [comment]
which version of monkey ?

On Wed, Mar 18, 2015 at 8:50 PM, Akhil a.k.a Enforcer007 <
notifications@github.com> wrote:

> Though "./configure --enable-shared" script is run followed by "make", lib
> folder is not created.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/monkey/monkey/issues/190>.
>



-- 
Eduardo Silva
http://edsiper.linuxchile.cl
http://monkey-project.com

**Comment by Enforcer007** [comment]
monkey-1.5.6

**Comment by edsiper** [comment]
its created inside src/

On Thu, Mar 19, 2015 at 9:18 AM, Akhil a.k.a Enforcer007 <
notifications@github.com> wrote:

> monkey-1.5.6
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/monkey/monkey/issues/190#issuecomment-83623546>.
>



-- 
Eduardo Silva
http://edsiper.linuxchile.cl
http://monkey-project.com
