### ISSUE TITLE
Fail to compile fresh github clone

### ISSUE THREAD

**Issue by mingodad** [monkey/monkey#191]
Hello !

I just did a fresh clone of monkey and run:
./configure --prefix=$HOME/local --enable-shared
make

and get this error:
gcc: error: ../plugins/liana/monkey-liana.a: No such file or directory

If I only run "./configure; make" it does compile with some warnings like:

mk_plugin.c:847:2: warning: #warning "FIXME: waiting for architecture changes" [-Wcpp]

Also even after compiling the examples do not compile, it seems that they are not updated to work with the master.

Cheers !

**Comment by edsiper** [comment]
if you specify a prefix, Monkey will expect to find the plugins on the prefix path, for hence it needs a make install after 'make'.
