### ISSUE TITLE
v1.6-dev: memory corruption on cleanup when HTTP parser detects a protocol error

### ISSUE THREAD

**Issue by gotojyh** [monkey/monkey#194]
if I use a phone download a file,it doesn't work,but in PC it's ok.
the monkey is running on Ubuntu 14.04

**Comment by edsiper** [comment]
please provide more details:

 - file size
 - Monkey version
 - any errors ?

**Comment by gotojyh** [comment]
file size:about 3.5M
monkey version:1.6
use an android(4.3) phone 
you  should find the error if you download a file(my file is 'a.apk.zip') with a phone(android)

**Comment by edsiper** [comment]
- Tested download a file of 7MB from Monkey 1.6 (git) running in my laptop and downloading over wifi to my Android phone. It worked.

Please reconfigure/compile Monkey with: ./configure --local --debug --trace, reproduce the issue  and provide the output.

**Comment by gotojyh** [comment]
ok,I will have a test

**Comment by gotojyh** [comment]
I catch it.
http request like this:
---------------------------------------------------------------------
GET /a.apk.zip HTTP/1.1\r\n
cookie: \r\n
Host: 192.168.100.69:2001\r\n
Connection: Keep-Alive\r\n
User-Agent: AndroidDownloadManager/4.4.2 (Linux; U; Android 4.4.2; MX4 Build/KOT49H)\r\n
----------------------------------------------------------------------

is this standard? this comes from an android phone.
and the error found in  the function "mk_http_parse_ok"
================================================
           else if (p->status == MK_ST_HEADER_VALUE) {
                /* Trim left, set starts only when found something != ' ' */
                if (buffer[i] == '\r' || buffer[i] == '\n') {
                    return MK_HTTP_PARSER_ERROR;
                }
=================================================

and the function will return MK_HTTP_PARSER_ERROR;
after the error,the monkey will not work again and print this
-----------------------------------------------------------------------------------------
[  Error] epoll_ctl: Bad file descriptor, errno=9 at /root/21/monkey/src/mk_event_epoll.c:114
 [  Error] epoll_ctl: No such file or directory, errno=2 at /root/21/monkey/src/mk_event_epoll.c:97
-----------------------------------------------------------------------------------------

**Comment by edsiper** [comment]
Thanks for catching this, I am investigating.

Btw, why the Cookie header don't have a value ?, is this intentional or a problem on your Android lib ?

**Comment by edsiper** [comment]
thanks again for report this problem, I have pushed a fix and seems to work fine now.
