### ISSUE TITLE
MK_UTILS_LIBC_ERRNO_BUFFER() would crash if called from main process

### ISSUE THREAD

**Issue by gotojyh** [monkey/monkey#195]
I found it doesn't call pthread_setspecific for mk_utils_error_key in main_thread,so when program calls mk_utils_libc_error in main thread,it will core dump

**Comment by edsiper** [comment]
thanks for catching that. 

Note for my self: the fix needs to take place in include/monkey/mk_utils.h:

```
#define MK_UTILS_LIBC_ERRNO_BUFFER()                                  \
    int _err  = errno;                                                \
    char *buf = pthread_getspecific(mk_utils_error_key);              \
    if (strerror_r(_err, buf, MK_UTILS_ERROR_SIZE) != 0) {            \
        mk_err("strerror_r() failed");                                \
    }
```

for every call, check if the running thread id is equal or not than the server process tid. If its different just use the thread key, otherwise set a static buffer.

**Comment by edsiper** [comment]
Monkey binary is a separate caller, the routine in question is not longer in use here.
