### ISSUE TITLE
Infinite loop on broken pipe

### ISSUE THREAD

**Issue by gotojyh** [monkey/monkey#200]
I found a issue,you may have a try to see whether it will occur
use a client to download a big file(eg. 500M) and break up before finishing downloading.

for example:
curl 192.168.1.2:2001/bigfile.tar
and ctrl+c curl
and monkey will print these:

[  Error] [FD 20] error from sendfile(): Broken pipe

and monkey will not work as normal.

**Comment by edsiper** [comment]
Broken pipe means the system lost connection with the peer. Is this happening on Android or from a PC?

**Comment by gotojyh** [comment]
both Android and PC
it will happen if you break up when downloading a file.
I don't know if that's your question
I am trying to find the reason

**Comment by edsiper** [comment]
Issue confirmed on v1.6 (GIT master)

**Comment by edsiper** [comment]
Thanks for catching up the problem.

The right solution for the case is to use ssize_t data type which allows negative values.
