### ISSUE TITLE
Why use red-black tree in mk_server?

### ISSUE THREAD

**Issue by neeraj9** [monkey/monkey#204]
I don't think that you need RB here, although I could be wrong since I spent only half an hour going through the code. It appears that you are just using the tree for insertion and deletion.

**Comment by edsiper** [comment]
Monkey v1.6 is being refactored and some parts are still there, If you look at 1.5.6 the RBT is used to handle all connections and further lookups. 

I need to determinate yet if at some point would be required to get the connection context when there is no event triggered, this can mostly happen from plugins such as Duda I/O, there is no final word as it's work in process.

**Comment by edsiper** [comment]
GIT master requires Red-black-tree (mimetype) and other sub-components I am adding.
