### ISSUE TITLE
Should sbin not be bin?

### ISSUE THREAD

**Issue by sbagmeijer** [monkey/monkey#216]
First of all this is not really a bug more a question and perhaps a discussion.

I noticed that when I was compiling Monkey 1.6.0 that the new configuration option is:
 --sbindir=BINDIR        Binary files (executables)

I also notice without any options Monkey will automatically select the following directory:
/usr/local/sbin/monkey

According to the "Filesystem Hierarchy Standard (FHS)" /usr/sbin or /usr/local/sbin is meant for binaries used by the system, and Monkey is not really a "system" application.

If we would follow the correct structure should we not use "/usr/bin" or "/usr/local/bin"?

In 1.5.6 it was correctly like this I am not sure what the reason was for the change?

As I said not really a bug more curious :)

**Comment by edsiper** [comment]
It could be a misunderstanding on my end, isn't a "web server" considered as a system service ?.

**Comment by sbagmeijer** [comment]
I think this explains it pretty good:
```
Linux Filesystem Structure
3.10 /sbin : System binaries

Utilities used for system administration (and other root-only commands) are stored in /sbin, /usr/sbin, and /usr/local/sbin. /sbin typically contains binaries essential for booting the system in addition to the binaries in /bin.
```

It is not very important I mean you give a override option with configure so was more curiosity that I asked this.

**Comment by edsiper** [comment]
I found this:

http://www.tldp.org/HOWTO/HighQuality-Apps-HOWTO/fhs.html

in the section 4.2 it suggest Apache binary can go in any please ; note that TCP port 80 requires root privileges.

--sbindir should work to override the path anyways.
