### ISSUE TITLE
./configure --enable-plugins=tls does not compile tls built-in plugin

### ISSUE THREAD

**Issue by J-Siu** [monkey/monkey#223]
monkey doesn't compile built-in tls plugin if configure with following option.
```
./configure --enable-plugins=tls
```
Result:
```
ubuntu@U64:~/monkey/build$ ./monkey -b
Monkey HTTP Server v1.7.0
Built : Dec 12 2015 02:21:47 (/usr/bin/cc 5.2.1)
Home  : http://monkey-project.com

[system: Linux]
Linux-4.2.0-19-generic

[configure]


[setup]
configuration dir: /home/ubuntu/monkey/build/conf/


[built-in plugins]
liana               Liana Network Layer
```

**Comment by edsiper** [comment]
Note that a built-in plugin means it was build statically. The option --enable-plugins=a,b,c instruct the build system to build the plugins, but they are build as shared library by default. If you want a built-in plugin you have to use the option:

```bash
$ ./configure --static-plugins=tls --enable-plugins=tls
```

**Comment by J-Siu** [comment]
Is ebed src still include in the master branch? Maybe I was brain dead last trying out stuff too late during the night. I was just so confuse with the result, lol

**Comment by edsiper** [comment]
mbedTLS is part of the sources of Monkey, if you enable the 'tls' plugin at build time, mbedtls will be build statically too:

```
$ ./configure --static-plugins=tls --enable-plugins=tls
```

**Comment by J-Siu** [comment]
I found the cause. I was using the master branch and "ssl" keyword, which has no effect, so monkey is not loading the share library, though I have it set to load in the plugins.load. That was a bit confusing.
