### ISSUE TITLE
tls plugin is loading files in current directory if no absolute path is given

### ISSUE THREAD

**Issue by J-Siu** [monkey/monkey#225]
According to tls.conf comment:
```
[TLS]
    # If no absolute path is given, files are assumed to be located
    # in plugin configuration directory. All files are assumed to be
    # stored in PEM format.
```
However if no absolute path is given, the plugin is trying to load files in current directory.

PS: Tested with "./configure --local --enable-plugins=tls --mbedtls-shared"

**Comment by edsiper** [comment]
Thanks for reporting this. I just applied a fix for this problem:

https://github.com/monkey/monkey/commit/9d996eb92c489eb215067295bc8930223e658d7f
