### ISSUE TITLE
dirlisting is not working

### ISSUE THREAD

**Issue by ulysses4ever** [monkey/monkey#275]
I ran `monkey`, and it says:

```
Monkey HTTP Server v1.6.9
Built : Jun  8 2017 16:38:28 (/usr/bin/cc 6.3.0)
Home  : http://monkey-project.com
[+] Process ID is 5163
[+] Server listening on 0.0.0.0:2001
[+] 8 threads, may handle up to 1024 client connections
[+] Loaded Plugins: liana dirlisting 
[+] Linux Features: TCP_FASTOPEN SO_REUSEPORT 
[2017/06/22 13:47:02] [   Info] HTTP Server started

```
It handles happily regular HTTP-requests for individual files. But `dirlisting` thing is not working: request to any directory without index file returns 403. Any thoughts how this can be fixed?

**Comment by edsiper** [comment]
Sorry for the delays, for more details please refer to #276
