### ISSUE TITLE
Forbidden Content-Length when method is not PUT or POST.

### ISSUE THREAD

**Issue by alkino** [monkey/monkey#279]
Hi,

I see here https://github.com/monkey/monkey/blob/75fd22d625fa9b2cee10aae5926d8ef4bb699144/mk_server/mk_http.c#L711-L715
That you forbidden content-length when method is not PUT or POST but it seems that in RFC nothing forbid to have an empty one. Even if there is no body.

Why?
Can we change that?

Regards,
Nicolas

**Comment by edsiper** [comment]
You are right, thanks for the hints. What I will do is just omit that header on that specific condition and not trigger the error.
