### ISSUE TITLE
Monkey running as non-root user runs php-cgi with root privileges

### ISSUE THREAD

**Issue by ajlennon** [monkey/monkey#355]
Hi all,

I have Monkey  v1.5.4 building under Yocto and have it configured to run as user `www-data`

It's configured to use the CGI plugin. I noticed that when a PHP script runs the command `php-cgi` runs up and this runs as user www-data (which seems correct)

However I then noticed that `php-cgi` is writing files in e.g. /home/root which should not be possible (imho)

We found this post on RUID/RGID which I suspect is what is happening.

Having PHP running with root privileges seems an attack vector that I need to avoid.

Can anybody suggest anything I can do to restrict the privileges of `php-cgi` ?

Thanks!

**Comment by leonardo-albertovich** [comment]
Hi @ajlennon I'm not really familiar with that part of monkey and I kind of doubt anyone will be able to take the time required to verify this in the short term. 

If I was in your place I would try to run monkey as an unprivileged user in a high port in the loopback interface and set up a firewall rule to forward the traffic to it. 

I could be wrong as I never used monkey as a stand alone web server so I don't know if there are other components that requires root access but that's the first thing that comes to my mind.

Quick questions  : 

1. Is the directory you're reading/writing really `/home/root/`? In that case, which distribution is it? I've never seen the root home being anything else but `/root` but I could be wrong.
2. Could you run stat with the file you're accessing as a target to get a proper breakdown of the ownership and permissions so we can be sure it's an impersonation issue?

**Comment by ajlennon** [comment]
Hi @leonardo-albertovich 

- Yes this is running on Yocto and this folder is only writeable by the root userr
- I'll set this up

I think that moving from CGI where the `php-cgi` process is started up to FastCGI with root privileges where Monkey interacts with the `php-fsl` process which is running as a non-root user should address the problem.

**Comment by ajlennon** [comment]
So I'm sure that `php-cgi` is running with root privileges with the CGI plugin.

Using the FastCGI plugin with `php-fsl` running as non-root user addresses this.

fwiw I'd suggest somebody updates the recommendation not to use CGI on production systems to include a not on this as it seems like a potentially huge security issue for people.
