### ISSUE TITLE
-DMK_PTHREAD_TLS=ON mode causes link failures on gcc-10 and above (-fno-common default)

### ISSUE THREAD

**Issue by trofi** [monkey/monkey#370]
It's a forward of https://github.com/fluent/fluent-bit/issues/5537 issue which uses `monkey` as a dependency

Reproducer (on `x86_64-linux`):

```
$ cmake .. -DMK_PTHREAD_TLS=ON
$ make
...
[ 87%] Linking C executable ../bin/monkey
ld: CMakeFiles/monkey-bin.dir/mk_signals.c.o:(.bss+0x0): multiple definition of `mk_tls_cache_iov_header'; CMakeFiles/monkey-bin.dir/monkey.c.o:(.bss+0x0): first defined here
ld: CMakeFiles/monkey-bin.dir/mk_signals.c.o:(.bss+0x4): multiple definition of `mk_tls_cache_header_cl'; CMakeFiles/monkey-bin.dir/monkey.c.o:(.bss+0x4): first defined here
ld: CMakeFiles/monkey-bin.dir/mk_signals.c.o:(.bss+0x8): multiple definition of `mk_tls_cache_header_lm'; CMakeFiles/monkey-bin.dir/monkey.c.o:(.bss+0x8): first defined here
...
```

Similar logs on `x86_64-darwin`: https://hydra.nixos.org/log/y9q3l83whwyp68rdclsbylz23263ffdd-fluent-bit-1.8.11.drv

Initially noticed build failure when attempted to switch OS distribution from `-fcommon` toolchain (`gcc-9`) to `-fno-common` toolchain (`gcc-10+`): https://gcc.gnu.org/PR85678

Moving variable definitions out of `monkey/mk_tls.h` should help.

Thank you!

**Comment by edsiper** [comment]
assigned to @leonardo-albertovich

**Comment by ThomasDevoogdt** [comment]
The same issue is seen on buildroot (GCC 12 - s390x / arch11 - fluent-bit-2.0.8 - glibc - Not static)
http://autobuild.buildroot.net/results/df9/df9901b7b52c7933e6a4ef4503f80e336e0e299e/build-end.log
http://autobuild.buildroot.net/results/11d/11dd5ddf9ab3cfd1464a212f4e3d923832d53462/build-end.log

**Comment by edsiper** [comment]
cc: @cosmo0920
