### ISSUE TITLE
Reduce memory footprint

### ISSUE THREAD

**Issue by sheh** [monkey/monkey#378]
I have a simple web application (single user, a couple pages) with a few requests per second. The server uses about 75Mb RAM for my application. 
Can I go even lower with memory usage according to described load?

**Comment by edsiper** [comment]
not sure how it's being used, but we primary support the library mode now.. what is your use case ?

sorry by the lack of docs around these changes in the  project.

**Comment by sheh** [comment]
I build binary for aarch64 like it is described [here](http://monkey-project.com/documentation/1.5/getting_started/installation.html). Then I run the binary on the target device and everything works fine. But I see lack of RAM due to I have only 200-250Mb free (the binary consumes ~75Mb + my app ~100-150Mb). 
It would be great if I could use some build option (or runtime option) to reduce memory consumption for monkey binary (like, number of workers, reduce buffering, turn off plugins, whatever...). 
I checked build doc and did not find any information about it. Did I miss something? Are there some "hidden" options?
Thanks!

**Comment by edsiper** [comment]
@sheh to be honest we are no longer maintaining the binary version, I would suggest to try another web server option.

**Comment by sheh** [comment]
oh, understood.
Thanks for help!
