### ISSUE TITLE
mk_server: race condition for `MK_SERVER_SIGNAL_START` between worker and main threads

### ISSUE THREAD

**Issue by braydonk** [monkey/monkey#380]
# Description

When running in library mode, there is a race condition between the worker thread and main thread in `mk_start`. This race condition exists in both scheduler modes, but is closer in `MK_SCHEDULER_FAIR_BALANCING` mode.
In `MK_SCHEDULER_FAIR_BALANCING` mode, the order goes something like this:

```
main thread             |worker
---------------------------------------------------
mk_start                |
mk_utils_worker_spawn   |mk_server_setup
                        |mk_server_loop
                        |mk_server_lib_notify_started // writes to lib_ch_manager socket
                        |mk_server_loop_balancer
mk_event_wait (lib_evl) |mk_event_wait (new event loop on lib_ch_manager socket) // this step is a race between threads!
```
If the worker thread reaches the mk_event_wait first, it will eat the `MK_SERVER_SIGNAL_START` signal sent by `mk_server_lib_notify_started`. In `MK_SCHEDULER_REUSEPORT` mode, the race is between the main thread and `mk_lib_worker`, however this race is almost always going to be won by the main thread because of a [preventative sleep(1)](https://github.com/monkey/monkey/blob/master/mk_server/mk_lib.c#L151).

When the worker thread wins the race, the main thread will sit waiting in perpetuity for the `MK_SERVER_SIGNAL_START` on the lib_ch_manager socket. This can cause the entire program to hang trying to start a monkey server. Under a majority of scenarios, the main thread will win the race. We only detected this issue while encountering what we can only assume is a strange scheduler behaviour in Windows Server 2012 R2 (see https://github.com/fluent/fluent-bit/issues/6275). However, the race condition can be forced on any platform by adding a malicious `sleep(4)` [before the main thread waits for the start signal](https://github.com/monkey/monkey/blob/master/mk_server/mk_lib.c#L198).

**Comment by qingling128** [comment]
@edsiper Is this something we could bring into Fluent Bit 1.9?

**Comment by edsiper** [comment]
hi @qingling128 , if this has been extensively tested in G side, yeah, definitely, we can schedule another 1.9 release.

**Comment by braydonk** [comment]
Hi @edsiper, I have done testing of this by using this [standalone test program](https://github.com/braydonk/monkey_test_program) and by patching it into Fluent Bit and using it in the Ops Agent, which uses a config that starts a monkey server using the Prometheus exporter ([see our default config here](https://github.com/GoogleCloudPlatform/ops-agent/blob/master/confgenerator/testdata/builtin/windows/golden_fluent_bit_main.conf)). I'm happy to test any other scenarios that might cover other use cases not covered by this.

**Comment by qingling128** [comment]
Hi @edsiper We’ve tested the custom build on GCE Windows 2012 and 2019 VMs with 10+ restarts, and the fix worked fine. We were able to reproduce the problem without the fix. So far, it looks good. What additional testing do you think is preferred? Is this sufficient?

**Comment by edsiper** [comment]
@qingling128 thanks for the clarification. would you please open a github issue in fluent/fluent-bit asking to upgrade lib/monkey ? (we handle the PR for that)
