### ISSUE TITLE
Multiple http server may cause SIGSEGV

### ISSUE THREAD

**Issue by nokute78** [monkey/monkey#394]
Fluent-bit uses monkey as a library.

https://github.com/fluent/fluent-bit/issues/7203
`mk_plugin_exit_all` causes SIGSEGV on exit.

In above case, fluent-bit creates two http servers.
- Fluent-bit http server for metrics
- out_vivo_exporter plugin

Note: If fluent-bit creates "one" server, the issue will not happen.
I think some race on exit causes this issue.

**Comment by leonardo-albertovich** [comment]
I just opened PR #395 to fix this issue.
