### ISSUE TITLE
Monkey version 1.7.0

### ISSUE THREAD

**Issue by eloydegen** [monkey/monkey#403]
It looks like the Fluentbit project includes version 1.7.0 of the Monkey web server, but this version does not seem to exists as a release or a tag here. The current master branch is on 1.7.0, according to the CMakeList: https://github.com/monkey/monkey/blob/master/CMakeLists.txt#L23

But if that is used in production by another project, then it would make sense to make it a release here as well. Also, probably not everyone is fully aware of the differences between the latest Git version and the release of almost 10 years old, which should not be used anymore nowadays.

**Comment by edsiper** [comment]
we have not tagged the project, you are right, we will start doing it. thanks

**Comment by edsiper** [comment]
(tagged)
