### ISSUE TITLE
given the website is down, provide all the docs that were referred to on the website - especially configuration

### ISSUE THREAD

**Issue by badbettty** [monkey/monkey#420]
as per title, plus ...

the instructions in the program build refer to consulting the 'more complete' docs on the website which no longer exists.

particulary interested in what can go in 'monkey.conf'    (e.g. is there a setting for plugins load file etc).

and/or perhaps, crucially, someone has an archive copy of the website they could link to.  :-)

cheers

**Comment by rtfmoz2** [comment]
You can view the documentation here - https://web.archive.org/web/20220327051924/http://www.monkey-project.com/

**Comment by rtfmoz2** [comment]
Also you can generate it here using the instructions provided - https://github.com/monkey/monkey-docs

**Comment by rtfmoz2** [comment]
Here is the documenation for windows and linux. Open index.html.
[monkey-docs-win.zip](https://github.com/user-attachments/files/18281158/monkey-docs-win.zip)
[monkey-docs.zip](https://github.com/user-attachments/files/18281159/monkey-docs.zip)

**Comment by badbettty** [comment]
@rtfmoz2   -  Thank you for doing that.   Much appreciated.    Best wishes for seeing in the new year and what it brings.
